#!/usr/bin/env bash

__zd_picker() {
  eval "${ZD_PICKER:-fzf}" "${ZD_PICKER_ARGS}"
}

__zd() {
  if [[ $# -eq 0 ]]; then
    local rc="${ZD_RC:-$HOME/.zdrc}"
    if [[ -x "$rc" ]]; then
      "$rc" | __zd_picker
    elif [[ -f "$rc" ]]; then
      # shellcheck disable=SC1090
      source "$rc" | __zd_picker
    else
      echo "$HOME"
    fi
  elif [[ $# -eq 1 ]]; then
    echo "$1"
  elif [[ $# -eq 2 && "$1" == "--" ]]; then
    echo "$2"
  fi
}

__zd_plugin_load() {
  [[ -d "$1" ]] || return

  [[ -f "$1/bin/bash/init" ]] || return
  # shellcheck disable=SC1091
  source "$1/bin/bash/init"

  # shellcheck disable=SC1091
  [[ -f "$1/bin/bash/alias" ]] && source "$1/bin/bash/alias"
}

__zd_plugin_load_all() {
  mkdir -p "${ZD_DIR:-$HOME/.zd}/plugins"
  find "${ZD_DIR:-$HOME/.zd}/plugins" -mindepth 1 -maxdepth 1 -type d | while read -r plugin; do
    __zd_plugin_load "$plugin"
  done
}

__zd_plugin_load_all
